---
version: '3'

services:
  jekyll:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/srv/jekyll
    env_file:
      - .env
    ports:
      - "80:4000"
  flask:
    build:
      context: .
      dockerfile: webhook/Dockerfile.flask
    env_file:
      - .env
    ports:
      - "5000:5000"
    links:
      - jekyll:jekyll
